apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: observation-json
  namespace: rest-fhir
spec:
  details:
    dataFormat: json
    connection:
      name: fhir
      fhir:
        fhirServer: 'https://fhir-sandbox.heirproject.eu/fhir-server/api/v4/'
        port: 9443
        namespace: rest-fhir
        secretRef: fhir-credentials
  secretRef:
      name: fhir-credentials
  metadata:
    name: consent
    geography: UK
    tags:
      healthcare: true
    columns:
      - name: id
        tags:
          PII: true
      - name: subject.reference
        tags:
          PII: true

