# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: app.fybrik.io/v1beta1
kind: FybrikModule
metadata:
  name: resttofhir
  namespace: fybrik-system
  labels:
    name: RESTToFHIR
    version: 0.1.0 
spec:
  type:  service  
  capabilities:
    - capability: read
      actions:
        - name: RedactColumn
        - name: Statistics
        - name: BlockResource
        - name: ReturnIntent
        - name: JoinResource
      supportedInterfaces:
        - source:
            protocol: fhir
            dataformat: json
  chart:
    name: ghcr.io/elsalant/rest-read-chart:0.0.2
    values:
      image.tag: instana
  statusIndicators:
    - kind: StreamTransfer
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error

