data:
{{- if .Values.copy -}}
    {{- if .Values.copy.source.connection.kafka }}
      WP2_TOPIC: {{ .Values.copy.source.connection.kafka.topic_name }}
      HEIR_KAFKA_HOST: {{ .Values.copy.source.connection.kafka.bootstrap_servers }}  
    {{- end }}
    {{- if .Values.copy.destination.connection.s3 }}
      VAULT_SECRET_PATH: {{ .Values.copy.destination.vault.secretPath }}
      SECRET_NSPACE: {{ .Values.copy.destination.credentialLocation.namespace }}
      SECRET_FNAME: {{ .Values.copy.destination.credentialLocation.secret_file }}
      S3_URL: {{if .Values.copy.destination.connection.s3.endpoint}}http://{{end}}{{ .Values.copy.destination.connection.s3.endpoint }}
    {{- end }}
    {{- if .Values.copy.source.transformations }}
    transformations:
    {{- $redactColumns := list -}}
    {{- $statisticsColumn := list -}}
    {{- $removeColumn := list -}}
    {{- range .Values.copy.source.transformations -}}
      {{- if eq .name "RedactColumn" -}}
        {{- $redactColumns = .RedactAction.columns -}}
      {{- end -}}
      {{- if eq .name "RemoveColumn" -}}
        {{- $removeColumns = .RemoveColumn.columns -}}
      {{- end -}}
      {{- if eq .name "Statistics" -}}
        {{- $statisticsColumn = .Statistics.columns -}}
      {{- end -}}
    {{- end -}}
    {{- if .Values.copy.source.transformations.RedactColumn }}
      - action: "RedactColumn"
        description: "redact columns: {{ $redactColumns }}"
        columns:
          {{- range $redactColumns}}
          - {{ . }}
          {{- end }}
        options:
          redactValue: "XXXXX"
    {{- end}}  # .Values.copy.source.transformations.RedactColumn
    {{- if .Values.copy.source.transformations.Statistics }}
      - action: "Statistics"
        description: "Perform statistical analysis on: {{ $statisticsColumn }}"
        columns:
          {{- range $statisticsColumn}}
          - {{ . }}
          {{- end }}
    {{- end}} # .Values.copy.source.transformations.Statistics
    {{- end }}  # if .Values.copy.source.transformations
{{- end -}}
